# Generated by Django 5.0.3 on 2024-06-29 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_alter_customuser_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='approvedinvoice',
            old_name='created_at',
            new_name='date_created',
        ),
        migrations.RenameField(
            model_name='pendinginvoice',
            old_name='created_at',
            new_name='date_created',
        ),
        migrations.RemoveField(
            model_name='approvedinvoice',
            name='approved_at',
        ),
        migrations.AlterField(
            model_name='approvedinvoice',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='pendinginvoice',
            name='description',
            field=models.TextField(),
        ),
    ]
