# Generated by Django 5.0.3 on 2024-06-29 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_rename_created_at_approvedinvoice_date_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvedinvoice',
            name='amount',
            field=models.PositiveIntegerField(),
        ),
    ]
