# Generated by Django 5.0.3 on 2024-07-24 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('billing', '0004_alter_approvedinvoice_amount'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={},
        ),
        migrations.AddIndex(
            model_name='approvedinvoice',
            index=models.Index(fields=['sender'], name='billing_app_sender__7580c9_idx'),
        ),
        migrations.AddIndex(
            model_name='approvedinvoice',
            index=models.Index(fields=['receiver'], name='billing_app_receive_562b2a_idx'),
        ),
        migrations.AddIndex(
            model_name='approvedinvoice',
            index=models.Index(fields=['date_created'], name='billing_app_date_cr_b007b8_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['email'], name='billing_cus_email_e6efa1_idx'),
        ),
        migrations.AddIndex(
            model_name='pendinginvoice',
            index=models.Index(fields=['sender'], name='billing_pen_sender__a827be_idx'),
        ),
        migrations.AddIndex(
            model_name='pendinginvoice',
            index=models.Index(fields=['receiver'], name='billing_pen_receive_84854b_idx'),
        ),
        migrations.AddIndex(
            model_name='pendinginvoice',
            index=models.Index(fields=['date_created'], name='billing_pen_date_cr_ac6c45_idx'),
        ),
    ]
